- name: Installing Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
- name: Placing Expense Config File
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Removing Old conten
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: creating new dircetiory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download and extract
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Starting Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes